version: '3.9'

services:
  lint-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: huma-signals-ci:latest
    command: ["make", "lint-check"]
    environment:
      - ENV=development

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: huma-signals-ci:latest
    environment:
      - ENV
      - ALCHEMY_KEY_GOERLI
    command: ["make", "test"]
