version: '3.9'

services:
  lint-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: huma-signals-ci:latest
    command: ["make", "lint-check"]
    environment:
      - ENV=development

  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: huma-signals-ci:latest
    command: ["make", "test"]
    environment:
      - ENV=test
      - CHAIN=GOERLI
      - SENTRY_DSN
      - DATADOG_API_KEY
      - WEB3_PROVIDER_URL
      - ETHERSCAN_API_KEY
      - ETHERSCAN_BASE_URL=https://api.etherscan.io
      - POLYGONSCAN_API_KEY
      - POLYGONSCAN_BASE_URL=https://api.polygonscan.com
      - REQUEST_NETWORK_SUBGRAPH_ENDPOINT_URL=https://api.thegraph.com/subgraphs/name/requestnetwork/request-payments-goerli
      - REQUEST_NETWORK_INVOICE_API_URL=http://rn-reader/invoice
    depends_on:
      - rn-reader

  rn-reader:
    image: 117773458657.dkr.ecr.us-west-1.amazonaws.com/dev-rn-reader:latest
    command: ["yarn", "server"]
    environment:
      - PROVIDER_URL
      - REQUEST_NODE_URL=https://goerli.gateway.request.network/
      - PORT=80
      - TIMEOUT=120000
      - RECEIVABLE_ADDRESS=0xC2AC172a293d68f548ea343414584aA37eb29Dcd
    ports:
      - '80'
