name: Huma DSP CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Lint
        run: docker-compose -f ./docker-compose-ci.yml run lint-tests

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: Unit and e2e tests
        run: |
          ALCHEMY_KEY_GOERLI="${{ vars.ALCHEMY_KEY_GOERLI }}" docker-compose -f ./docker-compose-ci.yml run tests
